# Generated by Django 2.2.14 on 2020-07-30 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assuntos',
            fields=[
                ('slug', models.SlugField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do assunto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Assunto',
                'verbose_name_plural': 'Assuntos',
            },
        ),
        migrations.CreateModel(
            name='Niveis',
            fields=[
                ('slug', models.SlugField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=50, verbose_name='Nivel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveis',
            },
        ),
        migrations.CreateModel(
            name='Perguntas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=254, verbose_name='Título da pergunta')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assunto', models.ManyToManyField(related_name='assunto', to='questoes.Assuntos')),
                ('niveis', models.ManyToManyField(related_name='niveis', to='questoes.Niveis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
            },
        ),
    ]
