# Generated by Django 2.2.14 on 2020-08-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguntas',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data'),
        ),
    ]
