# Generated by Django 2.2.14 on 2020-07-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(editable=False, max_length=50, verbose_name='Nome da Categoria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
