# Generated by Django 2.2.14 on 2020-07-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterField(
            model_name='categorias',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome da Categoria'),
        ),
    ]
