# Generated by Django 2.2.14 on 2020-07-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200727_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('slug', models.SlugField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Tags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
    ]
