# Generated by Django 2.2.14 on 2020-07-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome da Tag'),
        ),
    ]
