# Generated by Django 2.2.14 on 2020-08-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200729_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data'),
        ),
    ]
