# Generated by Django 2.2.14 on 2020-07-27 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostas',
            name='topico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='forum.Topicos'),
            preserve_default=False,
        ),
    ]
