# Generated by Django 2.2.14 on 2020-07-27 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=254, verbose_name='Título')),
                ('url', models.URLField(max_length=254, verbose_name='Url do canal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorias', models.ManyToManyField(related_name='canais', to='core.Categorias')),
                ('tags', models.ManyToManyField(related_name='canais', to='core.Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Canal',
                'verbose_name_plural': 'Canais',
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=254, verbose_name='Título')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorias', models.ManyToManyField(related_name='cursos', to='core.Categorias')),
                ('tags', models.ManyToManyField(related_name='cursos', to='core.Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('videoID', models.SlugField(max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='Url do canal')),
                ('titulo', models.CharField(max_length=254, verbose_name='Título')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='cursos.Canal')),
                ('categorias', models.ManyToManyField(related_name='videos', to='core.Categorias')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='cursos.Cursos')),
                ('tags', models.ManyToManyField(related_name='videos', to='core.Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
