# Generated by Django 2.2.14 on 2020-07-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='videoID',
            field=models.SlugField(max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='ID do Vídeo no Youtube'),
        ),
    ]
