# Generated by Django 2.2.14 on 2020-07-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=254, verbose_name='Título')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorias', models.ManyToManyField(related_name='categorias', to='core.Categorias')),
            ],
        ),
    ]
